import { Firefighter, Shift } from '../lib/supabase';

/**
 * Mock data for testing
 * Includes diverse scenarios: different positions, availability states, certifications
 */

export const mockFirefighters: Firefighter[] = [
  {
    id: 'ff-1',
    name: 'John Doe',
    order_position: 0,
    is_available: true,
    is_active: true,
    shift: 'A',
    fire_station: '1',
    last_hold_date: '2025-10-20T00:00:00Z',
    certification_level: 'FF2',
    apparatus_ambulance: true,
    apparatus_brush_truck: false,
    apparatus_engine: true,
    apparatus_tanker: false,
    apparatus_truck: true,
    apparatus_boat: false,
    apparatus_utv: false,
    apparatus_rescue_squad: false,
    is_fto: true,
    is_bls: true,
    is_als: false,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'ff-2',
    name: 'Jane Smith',
    order_position: 1,
    is_available: true,
    is_active: true,
    shift: 'A',
    fire_station: '2',
    last_hold_date: '2025-10-15T00:00:00Z',
    certification_level: 'FF1',
    apparatus_ambulance: true,
    apparatus_brush_truck: true,
    apparatus_engine: true,
    apparatus_tanker: false,
    apparatus_truck: false,
    apparatus_boat: false,
    apparatus_utv: true,
    apparatus_rescue_squad: false,
    is_fto: false,
    is_bls: true,
    is_als: false,
    created_at: '2025-01-02T00:00:00Z',
    updated_at: '2025-01-02T00:00:00Z',
  },
  {
    id: 'ff-3',
    name: 'Mike Johnson',
    order_position: 2,
    is_available: true,
    is_active: true,
    shift: 'A',
    fire_station: '1',
    last_hold_date: '2025-10-10T00:00:00Z',
    certification_level: 'FF2',
    apparatus_ambulance: false,
    apparatus_brush_truck: false,
    apparatus_engine: true,
    apparatus_tanker: true,
    apparatus_truck: true,
    apparatus_boat: false,
    apparatus_utv: false,
    apparatus_rescue_squad: true,
    is_fto: true,
    is_bls: false,
    is_als: true,
    created_at: '2025-01-03T00:00:00Z',
    updated_at: '2025-01-03T00:00:00Z',
  },
  {
    id: 'ff-4',
    name: 'Sarah Williams',
    order_position: 3,
    is_available: false, // Unavailable firefighter
    is_active: true,
    shift: 'A',
    fire_station: '2',
    last_hold_date: '2025-10-05T00:00:00Z',
    certification_level: 'FF1',
    apparatus_ambulance: true,
    apparatus_brush_truck: false,
    apparatus_engine: true,
    apparatus_tanker: false,
    apparatus_truck: false,
    apparatus_boat: true,
    apparatus_utv: false,
    apparatus_rescue_squad: false,
    is_fto: false,
    is_bls: true,
    is_als: false,
    created_at: '2025-01-04T00:00:00Z',
    updated_at: '2025-01-04T00:00:00Z',
  },
  {
    id: 'ff-5',
    name: 'Tom Brown',
    order_position: 4,
    is_available: true,
    is_active: true,
    shift: 'A',
    fire_station: null, // No station assigned
    last_hold_date: null, // Never held a shift
    certification_level: 'FF1',
    apparatus_ambulance: true,
    apparatus_brush_truck: false,
    apparatus_engine: false,
    apparatus_tanker: false,
    apparatus_truck: false,
    apparatus_boat: false,
    apparatus_utv: false,
    apparatus_rescue_squad: false,
    is_fto: false,
    is_bls: true,
    is_als: false,
    created_at: '2025-01-05T00:00:00Z',
    updated_at: '2025-01-05T00:00:00Z',
  },
];

// Shift B firefighters for shift isolation tests
export const mockFirefightersShiftB: Firefighter[] = [
  {
    id: 'ff-b1',
    name: 'Bob Anderson',
    order_position: 0,
    is_available: true,
    is_active: true,
    shift: 'B',
    fire_station: '1',
    last_hold_date: '2025-10-18T00:00:00Z',
    certification_level: 'FF2',
    apparatus_ambulance: true,
    apparatus_brush_truck: false,
    apparatus_engine: true,
    apparatus_tanker: false,
    apparatus_truck: true,
    apparatus_boat: false,
    apparatus_utv: false,
    apparatus_rescue_squad: false,
    is_fto: true,
    is_bls: true,
    is_als: false,
    created_at: '2025-01-06T00:00:00Z',
    updated_at: '2025-01-06T00:00:00Z',
  },
  {
    id: 'ff-b2',
    name: 'Alice Davis',
    order_position: 1,
    is_available: true,
    is_active: true,
    shift: 'B',
    fire_station: '2',
    last_hold_date: '2025-10-12T00:00:00Z',
    certification_level: 'FF1',
    apparatus_ambulance: true,
    apparatus_brush_truck: true,
    apparatus_engine: false,
    apparatus_tanker: false,
    apparatus_truck: false,
    apparatus_boat: false,
    apparatus_utv: false,
    apparatus_rescue_squad: false,
    is_fto: false,
    is_bls: true,
    is_als: false,
    created_at: '2025-01-07T00:00:00Z',
    updated_at: '2025-01-07T00:00:00Z',
  },
];

// Shift C firefighters for shift isolation tests
export const mockFirefightersShiftC: Firefighter[] = [
  {
    id: 'ff-c1',
    name: 'Charlie Wilson',
    order_position: 0,
    is_available: true,
    is_active: true,
    shift: 'C',
    fire_station: '1',
    last_hold_date: '2025-10-22T00:00:00Z',
    certification_level: 'FF2',
    apparatus_ambulance: false,
    apparatus_brush_truck: false,
    apparatus_engine: true,
    apparatus_tanker: true,
    apparatus_truck: false,
    apparatus_boat: false,
    apparatus_utv: false,
    apparatus_rescue_squad: false,
    is_fto: false,
    is_bls: false,
    is_als: false,
    created_at: '2025-01-08T00:00:00Z',
    updated_at: '2025-01-08T00:00:00Z',
  },
];

// Inactive firefighter for testing is_active filtering
export const mockInactiveFirefighter: Firefighter = {
  id: 'ff-inactive',
  name: 'Inactive User',
  order_position: 99,
  is_available: true,
  is_active: false,
  shift: 'A',
  fire_station: '1',
  last_hold_date: '2025-01-01T00:00:00Z',
  certification_level: 'FF1',
  apparatus_ambulance: false,
  apparatus_brush_truck: false,
  apparatus_engine: false,
  apparatus_tanker: false,
  apparatus_truck: false,
  apparatus_boat: false,
  apparatus_utv: false,
  apparatus_rescue_squad: false,
  is_fto: false,
  is_bls: false,
  is_als: false,
  created_at: '2025-01-09T00:00:00Z',
  updated_at: '2025-01-09T00:00:00Z',
};

// Helper function to create a firefighter with custom properties
export const createMockFirefighter = (
  overrides: Partial<Firefighter> = {}
): Firefighter => ({
  id: 'test-id',
  name: 'Test Firefighter',
  order_position: 0,
  is_available: true,
  is_active: true,
  shift: 'A',
  fire_station: '1',
  last_hold_date: null,
  certification_level: 'FF1',
  apparatus_ambulance: false,
  apparatus_brush_truck: false,
  apparatus_engine: false,
  apparatus_tanker: false,
  apparatus_truck: false,
  apparatus_boat: false,
  apparatus_utv: false,
  apparatus_rescue_squad: false,
  is_fto: false,
  is_bls: false,
  is_als: false,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  ...overrides,
});

// Mock scheduled hold data
export const mockScheduledHolds = [
  {
    id: 'hold-1',
    firefighter_id: 'ff-1',
    firefighter_name: 'John Doe',
    hold_date: '2025-11-01T00:00:00Z',
    status: 'scheduled' as const,
    shift: 'A' as Shift,
    fire_station: '1',
    notes: 'Vacation',
    created_at: '2025-10-20T00:00:00Z',
    updated_at: '2025-10-20T00:00:00Z',
    completed_at: null,
  },
  {
    id: 'hold-2',
    firefighter_id: 'ff-2',
    firefighter_name: 'Jane Smith',
    hold_date: '2025-11-05T00:00:00Z',
    status: 'scheduled' as const,
    shift: 'A' as Shift,
    fire_station: '2',
    notes: null,
    created_at: '2025-10-21T00:00:00Z',
    updated_at: '2025-10-21T00:00:00Z',
    completed_at: null,
  },
  {
    id: 'hold-3',
    firefighter_id: 'ff-1',
    firefighter_name: 'John Doe',
    hold_date: '2025-10-20T00:00:00Z',
    status: 'completed' as const,
    shift: 'A' as Shift,
    fire_station: '1',
    notes: 'Regular hold',
    created_at: '2025-10-15T00:00:00Z',
    updated_at: '2025-10-20T00:00:00Z',
    completed_at: '2025-10-20T12:00:00Z',
  },
];

// Mock activity log entries
export const mockActivityLog = [
  {
    id: 'log-1',
    firefighter_id: 'ff-1',
    firefighter_name: 'John Doe',
    action_type: 'hold_completed',
    details: 'Completed hold on 2025-10-20',
    shift: 'A' as Shift,
    created_at: '2025-10-20T12:00:00Z',
  },
  {
    id: 'log-2',
    firefighter_id: 'ff-2',
    firefighter_name: 'Jane Smith',
    action_type: 'firefighter_added',
    details: 'Added to Shift A roster',
    shift: 'A' as Shift,
    created_at: '2025-01-02T00:00:00Z',
  },
];
